name: db-update
on:
  push: 
  schedule:
    - cron: '0 * * * *'
    # Every hour, for now

jobs:
  update-databases:
    runs-on: ubuntu-latest    
    steps:
      - name: checkout repository
        uses: actions/checkout@v2    
      
      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: update jeremiah's todo list
        shell: bash
        env:
          DB_NAME: Jeremiah's TODO List
          DB_ID: ${{ secrets.DB_ID_JER_TODO }}
          TOKEN: ${{ secrets.TOKEN_JEREMIAH }}
        run: |
          python notion_automation/db_update.py "$TOKEN" "$DB_ID" "$DB_NAME"

      - name: update meera's todo list
        shell: bash
        env:
          DB_NAME: Meera's TODO List
          DB_ID: ${{ secrets.DB_ID_MEERA_TODO }}
          TOKEN: ${{ secrets.TOKEN_MEERA }}
        run: |
          python notion_automation/db_update.py "$TOKEN" "$DB_ID" "$DB_NAME"
  
