name: db-update
on:
  push:
  pull_request:
  schedule:
    - cron: '*/5 * * * *'
    # Every 5 minutes, for now

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      - name: checkout repository
        uses: actions/checkout@v2    
      
      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run script
        run: python helloworld.py
